### ISSUE TITLE
attempt to index global 'g' (a nil value)

### ISSUE THREAD

**Issue by lucax88x** [numToStr/BufOnly.nvim#1]
Hi, thanks for your plugin!

Unfortunately, I'm getting a weird error everytime I try to run the command :(

![Screenshot_2020-10-23_15-32-08](https://user-images.githubusercontent.com/6294464/97009940-0a9e3800-1545-11eb-99d4-a6aa1f004e41.png)

You have any idea what's going on?

**Comment by numToStr** [comment]
@lucax88x Thanks for the report. I forgot  the vim.g import. Now fixed. Please check.

**Comment by lucax88x** [comment]
Works, thanks.
