### ISSUE TITLE
Causes errors with nvim-treesitter-context

### ISSUE THREAD

**Issue by petertriho** [numToStr/BufOnly.nvim#2]
https://github.com/romgrk/nvim-treesitter-context/issues/47

After running BufOnly I get this error:
```
Error detected while processing CursorMoved Autocommands for "*":
E5108: Error executing lua ...start/nvim-treesitter-context/lua/treesitter-context.lua:210: Vim(lua):E5108: Error executing lua ...start/nvim-treesitter-con
text/lua/treesitter-context.lua:181: Invalid buffer id: 2
```
I do not have the same issue with https://github.com/schickling/vim-bufonly

**Comment by numToStr** [comment]
BufOnly permanently deletes the buffer maybe that's why this issue is coming. I am not using `romgrk/nvim-treesitter-context` so I am not that sure.

**Comment by petertriho** [comment]
Ah I think I know what's going on, probably can't do anything about. nvim-treesitter-context creates a scratch buffer that gets removed
